language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 3.5
    - 3.6

before_install:
  - uname -a

install:
  - pip install .[docs,tests]

before_script:
  - python -V

script:
  - py.test -v --cov=basis_set_exchange/

notifications:
  email: false

after_success:
  - codecov

