language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 3.5
    - 3.6

before_install:
  - uname -a

install:
  - pip install .[docs,tests] codecov

before_script:
  - python -V

script:
  - cd /tmp # Move to an unrelated dir
  - pytest --pyargs --cov=basis_set_exchange basis_set_exchange

notifications:
  email: false

after_success:
  - codecov

