package:
  name: basis_set_exchange
  version: "0.3.0"

source:
  path: ../..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - jsonschema

test:
  requires:
    - pytest
  imports:
    - basis_set_exchange

about:
  home: https://github.com/MolSSI-BSE/basis_set_exchange
  license: BSD-3-Clause License
